export type FontCategory = 'Sans Serif' | 'Serif' | 'Display' | 'Handwriting' | 'Monospace';

export const GOOGLE_FONTS: { name: string, category: FontCategory }[] = [
    // Sans Serif
    { name: 'Roboto', category: 'Sans Serif' },
    { name: 'Open Sans', category: 'Sans Serif' },
    { name: 'Lato', category: 'Sans Serif' },
    { name: 'Montserrat', category: 'Sans Serif' },
    { name: 'Oswald', category: 'Sans Serif' },
    { name: 'Source Sans Pro', category: 'Sans Serif' },
    { name: 'Slabo 27px', category: 'Sans Serif' },
    { name: 'Raleway', category: 'Sans Serif' },
    { name: 'PT Sans', category: 'Sans Serif' },
    { name: 'Poppins', category: 'Sans Serif' },
    { name: 'Ubuntu', category: 'Sans Serif' },
    { name: 'Inter', category: 'Sans Serif' },
    { name: 'Nunito', category: 'Sans Serif' },
    { name: 'Work Sans', category: 'Sans Serif' },
    { name: 'Fira Sans', category: 'Sans Serif' },
    { name: 'Quicksand', category: 'Sans Serif' },
    { name: 'Barlow', category: 'Sans Serif' },
    { name: 'Karla', category: 'Sans Serif' },
    { name: 'Rubik', category: 'Sans Serif' },
    { name: 'Josefin Sans', category: 'Sans Serif' },
    // Serif
    { name: 'Playfair Display', category: 'Serif' },
    { name: 'Merriweather', category: 'Serif' },
    { name: 'Lora', category: 'Serif' },
    { name: 'PT Serif', category: 'Serif' },
    { name: 'Noto Serif', category: 'Serif' },
    { name: 'Libre Baskerville', category: 'Serif' },
    { name: 'Crimson Text', category: 'Serif' },
    { name: 'Cormorant Garamond', category: 'Serif' },
    { name: 'EB Garamond', category: 'Serif' },
    { name: 'Vollkorn', category: 'Serif' },
    { name: 'Tinos', category: 'Serif' },
    { name: 'Zilla Slab', category: 'Serif' },
    { name: 'Arvo', category: 'Serif' },
    { name: 'Alegreya', category: 'Serif' },
    // Display
    { name: 'Lobster', category: 'Display' },
    { name: 'Abril Fatface', category: 'Display' },
    { name: 'Righteous', category: 'Display' },
    { name: 'Fredoka One', category: 'Display' },
    { name: 'Comfortaa', category: 'Display' },
    { name: 'Bebas Neue', category: 'Display' },
    { name: 'Cinzel', category: 'Display' },
    { name: 'Lilita One', category: 'Display' },
    { name: 'Titan One', category: 'Display' },
    { name: 'Fugaz One', category: 'Display' },
    // Handwriting
    { name: 'Dancing Script', category: 'Handwriting' },
    { name: 'Pacifico', category: 'Handwriting' },
    { name: 'Caveat', category: 'Handwriting' },
    { name: 'Satisfy', category: 'Handwriting' },
    { name: 'Great Vibes', category: 'Handwriting' },
    { name: 'Sacramento', category: 'Handwriting' },
    { name: 'Yellowtail', category: 'Handwriting' },
    { name: 'Kalam', category: 'Handwriting' },
    { name: 'Courgette', category: 'Handwriting' },
    { name: 'Leckerli One', category: 'Handwriting' },
    // Monospace
    { name: 'Roboto Mono', category: 'Monospace' },
    { name: 'Inconsolata', category: 'Monospace' },
    { name: 'Source Code Pro', category: 'Monospace' },
    { name: 'Space Mono', category: 'Monospace' },
    { name: 'Fira Code', category: 'Monospace' },
    { name: 'JetBrains Mono', category: 'Monospace' },
    { name: 'Anonymous Pro', category: 'Monospace' },
    { name: 'VT323', category: 'Monospace' },
];
